export { useLoginQuery } from './authorization/useLoginQuery'
export { useUsersQuery } from './user/useUsersQuery'
export { useCourseQuery } from './course/useCourseQuery'
export { useCoursesQuery } from './course/useCoursesQuery'
export { useWorkoutQuery } from './workout/useWorkoutQuery'
export { useWorkoutsQuery } from './workout/useWorkoutsQuery'
